before_script:  "bundle exec test/dummy/script/rails g clover_cms:dashboard:install"
script:         "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - ree

notifications:
  recipients:
    - enrique@cloverinteractive.com
    - alejandro@cloverinteractive.com
