script: "cd test/dummy && bundle exec rails g clover_cms:dashboard:install && cd ../../ && rake"
rvm:
  - 1.8.7
  - 1.9.2
  - jruby
  - ree
notifications:
  recipients:
    - enrique@cloverinteractive.com
    - alejandro@cloverinteractive.com